
spring:
  redis:
    # REDIS_URL
    url: redis://localhost:testpassword123@localhost:6379
    # 如果有密码
    password: testpassword123
    # 存储到分区1
    database: 1
    # 默认超时2000
    timeout: 3000

server:
  port: 88

#logging:
#    level:
#      com.example.demo.ffmpeg.FFmpegPublish: error
